version: '3'

services:
  mail:
    image: cd2team/mailhog:latest
    #image: mailhog/mailhog:v1.0.1
    container_name: contrast.mail
    environment:
      - TZ=Asia/Tokyo
      - MH_UI_WEB_PATH=mail
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/tmp
    volumes:
      - maildir:/tmp

  mysql:
    #image: mysql:8.0.21
    image: arm64v8/mysql:8.4.4
    container_name: contrast.mysql
    command: --local-infile=1 --log-bin-trust-function-creators=ON --innodb-buffer-pool-size=4G
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=default1!
      - MYSQL_DATABASE=contrast
      - MYSQL_USER=contrast
      - MYSQL_PASSWORD=password
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

  teamserver:
    #image: ghcr.io/contrast-security-inc/contrast:latest
    #image: ghcr.io/contrast-security-inc/contrast:3.12.2.14624369711@sha256:e9ecb599684ef57f00de55081fa2a0cb046d0524ec47b1137bfe404efe714739
    image: ghcr.io/contrast-security-inc/contrast:3.12.3.15305333654@sha256:a843ee79db7738e3885f10b1aab8806547631fa9d5d1474492ada732ae2446ba
    container_name: contrast.teamserver
    depends_on:
      #- mail
      - mysql
    expose:
      - '8080'
    #ports:
    #  - 8080:8080
    environment:
      - TZ=Asia/Tokyo
    # LICENCE Setup:
      - CONTRAST_LICENSE=${CONTRAST_LICENSE}   #loaded via ENV
      # Use Hub account to pull license
      #- CONTRAST_HUB_USERNAME=xxxxx.yyyyy@contrastsecurity.com
      #- CONTRAST_HUB_PASSWORD=XXXXXXXXXXXX
    # MySQL Setup: 
      # FOR REMOTE MySQL
      # - CONTRAST_JDBC_URL=jdbc:mysql://<DNS of MYSQL>:3306/contrast
      # - CONTRAST_JDBC_USER=contrast
      # - CONTRAST_JDBC_PASS=<PASSWORD>
      # FOR LOCALHOST MySQL
      # - CONTRAST_JDBC_URL=jdbc:mysql://host.docker.internal:3306/contrast
      # - CONTRAST_JDBC_USER=contrast
      # - CONTRAST_JDBC_PASS=<PASSWORD>
      # For a MySQL Container  --Uncomment 6 thru 15 and 20 & 21 along with the lines below.
      - CONTRAST_JDBC_URL=jdbc:mysql://mysql:3306/contrast
      - CONTRAST_JDBC_USER=contrast
      - CONTRAST_JDBC_PASS=password
    # SAML Setup
      # - CONTRAST_AUTHENTICATOR_SAML_KEYSTORE_PASSWORD=changeit
      # - CONTRAST_AUTHENTICATOR_SAML_KEYSTORE_PASSWORDMAP=some-alias=changeit
    volumes:
      #- ./contrast_conf:/opt/contrast/conf
      - contrast_data:/opt/contrast/data
    deploy: 
      resources:
        limits:
          cpus: "2.0"
          memory: 8g
        reservations:
          cpus: "1.0"
          memory: 4g

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: contrast.phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      MYSQL_ROOT_PASSWORD: default1!
      MYSQL_DATABASE: contrast
      MYSQL_USER: contrast
      MYSQL_PASSWORD: password
    depends_on:
      - mysql

  nginx:
    #image: nginx:1.13
    image: arm64v8/nginx:1.13
    container_name: contrast.nginx
    depends_on:
      - teamserver
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d

volumes:
  contrast_data: {}
  mysql_data: {}
  maildir: {}

